export const Calendarly = "https://calendly.com/functorfactory/30min"
export const Github = "https://github.com/FunctorFactory"
export const Twitter = "https://twitter.com/FunctorFactory"
export const LinkedIn = "https://www.linkedin.com/company/functor-factory"
export const YouTube = "https://www.youtube.com/@FunctorFactory"
export const Email = "mailto:jshilling@functorfactory.com"