on:
    pull_request:
    push:
        branches:
            - main

jobs:
    docker:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup AWS ECR
              uses: aws-actions/configure-aws-credentials@v1
              if: github.ref == 'refs/heads/main'
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ vars.AWS_REGION }}
            - name: Login to AWS ECR
              id: login
              if: github.ref == 'refs/heads/main'
              uses: aws-actions/amazon-ecr-login@v1
            - name: Build Docker Image
              if: github.ref == 'refs/heads/main'
              env:
                  REGISTRY: ${{ steps.login.outputs.registry }}
                  REPOSITORY: ${{ vars.ECR_REGISTRY }}
                  IAMGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IAMGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IAMGE_TAG
            - name: Build Docker Image
              if: github.ref != 'refs/heads/main'
              run: |
                docker build .