name: Verify PR

on:
  pull_request:
    types: [opened, synchronized, reopened]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'eslint.config.js'
      - 'tsconfig.json'
      - '**.ts'
  workflow_dispatch:

jobs:
  verify:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 'lts/*'
          check-latest: true
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
